// src/pages/create/index.tsx
import React, { useContext, useState } from 'react'
import {
  Button,
  Form,
  Input,
  TextArea,
  CascadePicker,
  Modal, Dialog,Checkbox
} from 'antd-mobile'
import { GlobalState } from '../../App'
import { updateListApi } from '../../services/api'
import { useNavigate,Link } from 'react-router-dom'

const Create: React.FC = () => {
  const { state } = useContext<any>(GlobalState)
  const [pickerVisible, setPickerVisible] = useState(false)
  const [submitLoading, setSubmitLoading] = useState(false)
  const [checked, setChecked] = useState(false)
  const navigate = useNavigate()
  const handleSubmit = (params: any) => {
    if(!checked){
      Dialog.alert({
        content: '请先勾选协议',
        onConfirm: () => {},
      })
      return
    }
    Modal.confirm({
      content: '确认要提交吗？',
      onConfirm: () => {
        setSubmitLoading(true)
        updateListApi({
          ...params,
          city: params.city[1],
          userInfo: state.userInfo,
        }).then((res) => {
          console.log(res)
          //@ts-ignore
          if (res?.errcode) {
            Dialog.alert({
              content: '内容可能含有违法违规内容',
              onConfirm: () => {},
            })
          } else {
            Dialog.alert({
              content: '保存成功',
              onConfirm: () => {
                navigate(-1)
              },
            })
          }
        }).finally(() => {
          setSubmitLoading(false)
        })
      },
    })
  }

  console.log(state)
  return <Form
    layout="horizontal"
    footer={
      <>
        <Checkbox
          checked={checked}
          onChange={(val)=>setChecked(val)}
          style={{
            '--icon-size': '18px',
            '--font-size': '14px',
            '--gap': '6px',
            marginBottom:8
          }}
        >
          勾选代表已阅读并同意<Link to="/statement">相关条款</Link>
        </Checkbox>
        <Button block type="submit" color="primary" loading={submitLoading}>
          提交
        </Button>
      </>
    }
    onFinish={(values) => {
      handleSubmit(values)
    }}
  >
    <Form.Item
      name="company"
      label="公司名称"
      rules={[{ required: true, message: '公司名称不能为空' }]}
    >
      <Input placeholder="请输入公司名称"/>
    </Form.Item>
    <Form.Item
      name="city"
      label="城市"
      rules={[{ required: true, message: '城市不能为空' }]}
      trigger="onConfirm"
      onClick={() => {
        setPickerVisible(true)
      }}
    >
      <CascadePicker
        title="城市选择"
        options={state.cityList}
        visible={pickerVisible}
        onClose={() => {
          setPickerVisible(false)
        }}
      >{value => value.length
        ? value.map((i: any) => i.label).join('/')
        : '请选择城市'}</CascadePicker>
    </Form.Item>
    <Form.Item name="content" rules={[{ required: true, message: '内容不能为空' }]}>
      <TextArea placeholder="请输入内容" maxLength={2000} rows={4}/>
    </Form.Item>
  </Form>
}

export default Create

// old/src/pages/create/index.vue
<template>
  <view class="">
    <view v-show="!system.show" class="u-padding-40">
      <u-empty text="该功能目前已下线" mode="permission"></u-empty>
    </view>
    <view v-show="system.show" class="u-padding-30">
      <u-form :model="model" ref="uForm" :errorType="['toast']">
        <u-form-item label="公司名称" label-width="130" prop="company">
          <u-input border placeholder="公司名称" v-model="model.company" />
        </u-form-item>
        <u-form-item label="所在城市" label-width="130" prop="city">
          <u-input type="select" :select-open="selectShow" v-model="model.city" placeholder="请选择所在城市"
            @click="selectShow = true"></u-input>
          <u-select v-model="selectShow" mode="mutil-column-auto" :list="cityList" @confirm="selectConfirm"></u-select>
        </u-form-item>
        <u-form-item label-width="0" prop="content">
          <u-input type="textarea" maxlength="5000" border placeholder="该公司不合理的地方…" v-model="model.content" />
        </u-form-item>
      </u-form>
      <view class="agreement">
        <u-checkbox v-model="check"></u-checkbox>
        <view class="agreement-text">
          勾选代表已阅读并同意
          <navigator url="../statement/index">相关条款</navigator>
        </view>
      </view>
      <u-button type="primary" :loading="loading" @click="submit">提交</u-button>
    </view>
  </view>
</template>

<script>
  const rules = {
    company: [{
      required: true,
      message: '请输入公司名称',
      trigger: 'blur',
    }],
    city: [{
      required: true,
      message: '请选择城市',
      trigger: 'blur',
    }],
    content: [{
      required: true,
      message: '请输入内容',
      trigger: 'blur',
    }],
  }
  export default {
    data() {
      return {
        model: {
          company: '',
          content: '',
          city: '',
        },
        check: false,
        loading: false,
        selectShow: false,
        cityList: [],
        system: {}
      };
    },
    async onLoad() {
      this.system = await getApp().getConfig()
      getApp().getCityList().then(r => {
        this.cityList = r
      })
    },
    onReady() {
      this.$refs.uForm.setRules(rules);
    },
    methods: {
      submit() {
        this.$refs.uForm.validate(valid => {
          if (valid) {
            if (!this.check) return this.$u.toast('请勾选协议');
            uni.showModal({
              content: '是否确认提交',
              success: (r) => {
                if (r.confirm) {
                  this.confirmSubmit()
                }
              }
            })
          } else {
            console.log('验证失败');
          }
        });
      },
      async confirmSubmit() {
        const userInfo = await getApp().getUserInfo()
        if (userInfo) {
          this.loading = true
          this.$u.http.post('list/update', {
            ...this.model,
            userInfo
          }).then(res => {
            console.log(res)
            if (res.errcode) {
              uni.showToast({
                icon: 'none',
                title: '内容可能含有违法违规内容'
              })
            } else {
              uni.showModal({
                content: '提交成功',
                showCancel: false,
                success: () => {
                  uni.navigateBack()
                }
              })
            }
          }).finally(() => {
            this.loading = false
          })
        }
      },
      selectConfirm(e) {
        if (e && e.length) {
          this.model.city = e[e.length - 1].value
        }
      },
    }
  };
</script>

<style lang="scss">
  @import 'style'
</style>
