// src/pages/about/index.vue
<template>
  <view>
    <view class="u-flex user-box u-p-l-30 u-p-r-20 u-p-b-30">
      <view class="u-m-r-10" :style=" {width: '60px', height: '60px', marginRight: '10px' }">
        <open-data type="userAvatarUrl"></open-data>
      </view>
      <view class="u-flex-1">
        <!-- <view class="u-font-18 u-p-b-20">IT民工</view> -->
        <view class="u-font-14 u-tips-color">如果你觉得小程序还不错，分享给你身边的IT从业者，或者请作者喝杯茶。</view>
      </view>
    </view>
    <u-gap></u-gap>
    <u-cell-group class="u-m-t-20">
      <navigator url="../create/index">
        <u-cell-item icon="edit-pen-fill" title="贡献一条黑名单"></u-cell-item>
      </navigator>
      <navigator url="../feedback/index">
        <u-cell-item icon="email-fill" title="留言"></u-cell-item>
      </navigator>
      <navigator url="../statement/index">
        <u-cell-item icon="info-circle-fill" title="特别声明"></u-cell-item>
      </navigator>
      <u-cell-item @click="handleOpen()" icon="github-circle-fill" title="GitHub"></u-cell-item>
      <u-cell-item @click="clickImg()" icon="gift-fill" title="打赏"></u-cell-item>
    </u-cell-group>
  </view>
</template>

<script lang="ts">
  export default {
    data() {
      return {

      }
    },
    methods: {
      handleOpen() {
        uni.showModal({
          title: 'https://github.com/liujiayii/',
          content: '点击确认按钮复制链接到浏览器中查看',
          showCancel:false,
          success: (r) => {
            if (r.confirm) {
              uni.setClipboardData({
                data: 'https://github.com/liujiayii/'
              })
            }
          }
        })
      },
      clickImg  ()  {
        uni.previewImage({
          urls: ['https://6974-itblacklist-1257941888.tcb.qcloud.la/qrcode.jpg?sign=a8a70c8edfa00f789149be669dce239f&t=1576917029',
            'https://6974-itblacklist-1257941888.tcb.qcloud.la/wx.jpg?sign=00f84fae613588571776b4a3570f63f1&t=1576917059']
        })
      }
    }
  }
</script>

<style lang="scss">
  page {
    background-color: #ededed;
    min-height: 100vh;
  }

  .user-box {
    background-color: #fff;
  }
</style>

// src/pages/about/index.jsx
import React, { Component } from 'react'
import { View, previewImage, setClipboardData, getClipboardData, showToast } from 'remax/wechat'
import Dialog from '@vant/weapp/dist/dialog/dialog'
import { shareInfo } from '@/utils/utils'
import VanCellGroup from '@vant/weapp/dist/cell-group'
import VanCell from '@vant/weapp/dist/cell'
import VanDialog from '@vant/weapp/dist/dialog'
import CustomTabBar from '@/custom-tab-bar'

export default class About extends Component {
  clickImg () {
    previewImage({
      urls: ['https://6974-itblacklist-1257941888.tcb.qcloud.la/qrcode.jpg?sign=a8a70c8edfa00f789149be669dce239f&t=1576917029',
        'https://6974-itblacklist-1257941888.tcb.qcloud.la/wx.jpg?sign=00f84fae613588571776b4a3570f63f1&t=1576917059'], //需要预览的图片http链接列表，注意是数组
      current: '', // 当前显示图片的http链接，默认是第一个
    })
  }

  handleOpen () {
    Dialog.confirm({
      title: '提示',
      message: 'Github:"https://github.com/liujiayii/" 点击确认按钮复制链接到浏览器中查看'
    }).then(() => {
      setClipboardData({
        data: 'https://github.com/liujiayii/'
      }).then(r => getClipboardData({
        success: () => {
          showToast({ title: '复制成功' })
        }
      }))
    }).catch(() => {})
  }

  onShareAppMessage () {
    return shareInfo
  }

  render () {
    return (
      <View className='index about'>
        <View className='top'>
          <View className='logo'>
            <View className='iconfont icon-bixin' style={{ color: '#f00', fontSize: '40px' }}/>
          </View>
          <View className='info'>如果你觉得小程序还不错，分享给你身边的IT从业者，或者请作者喝杯茶。</View>
        </View>
        <View style={{ marginTop: '10px' }}>
          <VanDialog id='van-dialog'/>
          <VanCellGroup>
            <VanCell title='贡献一条黑名单' is-link url='/pages/blackNew/index'>
              <View slot='icon' className='iconfont icon-ziyuan'/>
            </VanCell>
            <VanCell title='留言' is-link url='/pages/feedback/index'>
              <View slot='icon' className='iconfont icon-fankui-tianchong'/>
            </VanCell>
            <VanCell title='特别声明' is-link url='/pages/statement/index'>
              <View slot='icon' className='iconfont icon-jinggao'/>
            </VanCell>
            <VanCell title='GitHub' is-link onclick={() => this.handleOpen()}>
              <View slot='icon' className='iconfont icon-github'/>
            </VanCell>
            <VanCell title='打赏' is-link onclick={() => this.clickImg()}>
              <View slot='icon' className='iconfont icon-juanzeng'/>
            </VanCell>
          </VanCellGroup>
        </View>
        <CustomTabBar/>
      </View>
    )
  }
}
