// src/pages/content/index.tsx
import React, { useContext, useEffect, useState } from 'react'
import {
  Card,
  NavBar,
  Button,
  List,
  Toast,
  Dialog,
  Modal,
  Checkbox, Form, TextArea,
} from 'antd-mobile'
import { MessageFill, SmileFill, FrownFill } from 'antd-mobile-icons'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import qs from 'query-string'
import {
  getListApi,
  getDiscussApi,
  updateDiscussApi,
  updateListApi
} from '../../services/api'
import styles from './index.module.less'
import dayjs from 'dayjs'
import { GlobalState } from '../../store'

const Content: React.FC = () => {
  const { state } = useContext<any>(GlobalState)
  const location = useLocation()
  const navigate = useNavigate()
  const [detail, setDetail] = useState<any>({})
  const [discussList, setDiscussList] = useState([])
  const [submitLoading, setSubmitLoading] = useState(false)
  const [checked, setChecked] = useState(false)
  const getDiscussList = (company: string) => {
    getDiscussApi({
      company,
      current: 1,
      pageSize: 100,
    }).then((res: any) => {
      setDiscussList(res)
      console.log(res)
    })
  }
  const handleSubmit = (params: any) => {
    if (!checked) {
      Dialog.alert({
        content: '请先勾选协议',
        onConfirm: () => {},
      })
      return
    }
    Modal.confirm({
      content: '确认要提交吗？',
      onConfirm: () => {
        setSubmitLoading(true)
        updateDiscussApi({
          ...params,
          userInfo: state.userInfo,
          company: detail.company,
        }).then((res) => {
          console.log(res)
          //@ts-ignore
          if (res?.errcode) {
            Dialog.alert({
              content: '内容可能含有违法违规内容',
              onConfirm: () => {},
            })
          } else {
            Dialog.alert({
              content: '保存成功',
              onConfirm: () => {
                getDiscussList(detail.company)
              },
            })
          }
        }).finally(() => {
          setSubmitLoading(false)
        })
      },
    })
  }
  const getList = (needDiscuss?: boolean) => {
    const params = qs.parse(location.search) as { _id: string }
    getListApi(params).then((res: any) => {
      setDetail(res[0])
      if(needDiscuss){
        getDiscussList(res[0].company)
      }
    })
  }
  useEffect(() => {
    getList(true)
  }, [])
  const back = () => {
    navigate('/')
  }
  const appeal = () => {
    Modal.confirm({
      content: '如果内容有误，可以点此纠错，请具体到哪家公司、哪条评论',
      onConfirm: () => {
        navigate(`/feedback?_id=${detail._id}&company=${detail.company}`)
      },
    })
  }
  const updateRate = (type: number) => {
    updateListApi({
      _id: detail._id,
      rate: {
        type,
        userInfo: state.userInfo
      }
    }).then(()=>{
      getList()
      Toast.show('评价成功')
    })
  }
  const rateConfig = () => {
    const openid = state.userInfo.openid || ''
    const rate = detail.rate || []
    const rateUp = rate.filter((item: any) => item.type === 1)
    const rateDown = rate.filter((item: any) => item.type === -1)
    const isRate = [...rateUp, ...rateDown].findIndex(
      item => item.userInfo.openid === openid) !== -1
    return <>
      <Button onClick={() => updateRate(isRate ? 0 : 1)} size="small"
              color={isRate ? 'success' : 'default'} shape="rounded">
        {isRate ? <div style={{padding:'0 6px'}}><SmileFill style={{paddingRight: 4}}/>{rateUp.length}</div> : '有价值'}
      </Button>
      <Button onClick={() => updateRate(isRate ? 0 : -1)} size="small"
              color={isRate ? 'danger' : 'default'} shape="rounded">
        {isRate ? <div style={{padding:'0 6px'}}><FrownFill style={{paddingRight: 4}}/>{rateDown.length}</div> : '无价值'}
      </Button>
    </>
  }
  return <div className={styles.page_content}>
    <NavBar onBack={back}/>
    <Card title={detail.company}
          extra={`${dayjs(detail.createTime).format('YYYY-MM-DD HH:mm')}`}
          bodyStyle={{ fontSize: 18, paddingBottom: 40 }}>
      {detail.content}
      <Button color="primary" fill="none" style={{ float: 'right' }}
              onClick={() => appeal()}>
        我要纠错
      </Button>
    </Card>
    <div className={styles.btn_wrap}>
      {rateConfig()}
    </div>
    <div className={styles.discuss_title}><MessageFill/>精选评论</div>
    <List>
      {discussList.map((item: any) => <List.Item key={item._id}>
        <div onClick={() => Toast.show(`发表时间:${dayjs(item.createTime).
          format('YYYY-MM-DD HH:mm:ss')}`)}>{item.content}</div>
      </List.Item>)}
    </List>
    <Form
      style={{ marginTop: 20 }}
      layout="horizontal"
      footer={
        <>
          <Checkbox
            checked={checked}
            onChange={(val) => setChecked(val)}
            style={{
              '--icon-size': '18px',
              '--font-size': '14px',
              '--gap': '6px',
              marginBottom: 8,
            }}
          >
            勾选代表已阅读并同意<Link to="/statement">相关条款</Link>
          </Checkbox>
          <Button block type="submit" color="primary" loading={submitLoading}>
            提交
          </Button>
        </>
      }
      onFinish={(values) => {
        handleSubmit(values)
      }}
    >
      <Form.Item name="content" rules={[{ required: true, message: '内容不能为空' }]}>
        <TextArea placeholder="我要评论…" maxLength={2000} rows={4}/>
      </Form.Item>
    </Form>

  </div>
}

export default Content

// src/pages/content/index.vue
<template>
  <view class="">
    <u-card :title="content.company" :sub-title="$u.timeFormat(content.createTime, 'yyyy/mm/dd hh:MM')" full>
      <view class="content" slot="body">
        <view class="u-body-item">
          <view class="u-body-item-title">{{content.content}}</view>
          <view class="appeal-wrap"><text @click="appeal">我要纠错</text></view>
        </view>
      </view>
      <view class="" slot="foot" v-show="system.show">
        <view class="rate-wrap">
          <u-button :type="rateConf.up.type" shape="circle" size="medium" @click="updateRate(rateConf.up.rate)"
            style="width:119px">
            <u-icon v-show="rateConf.up.iconShow" name="thumb-up-fill" size="32"></u-icon>
            <text>{{rateConf.up.text}}</text>
          </u-button>
          <u-button :type="rateConf.down.type" shape="circle" size="medium" @click="updateRate(rateConf.down.rate)"
            style="width:119px">
            <u-icon v-show="rateConf.down.iconShow" name="thumb-down-fill" size="32"></u-icon>
            <text>{{rateConf.down.text}}</text>
          </u-button>
        </view>
        <u-icon name="chat-fill" size="34" label="精选评论"></u-icon>
        <u-empty v-if="!discussList.length" text="暂无评论" mode="news"></u-empty>
        <view v-for="(item,index) of discussList" :key="item._id"
          :class="[{'u-border-bottom':(index+1)!==discussList.length},'u-body-item']" style="margin-top: 8px;">
          <view class="u-body-item-title" @click="showTime(item.createTime)">{{item.content}}</view>
        </view>
      </view>
    </u-card>
    <view v-show="system.show" class="u-padding-30">
      <u-form :model="model" ref="uForm" :errorType="['toast']">
        <u-form-item label-width="0" prop="content">
          <u-input type="textarea" maxlength="2000" border placeholder="我要评论…" v-model="model.content" />
        </u-form-item>
      </u-form>
      <view class="agreement">
        <u-checkbox v-model="check"></u-checkbox>
        <view class="agreement-text">
          勾选代表已阅读并同意
          <navigator url="../statement/index">相关条款</navigator>
        </view>
      </view>
      <u-button :loading="loading" type="primary" @click="submit">提交</u-button>
    </view>
  </view>
</template>

<script>
  const rules = {
    content: [{
      required: true,
      message: '请输入内容',
      trigger: 'blur',
    }],
  }
  export default {
    data() {
      return {
        content: {},
        discussList: [],
        model: {
          content: ''
        },
        check: false,
        loading: false,
        system: {},
        userInfo: {}
      };
    },
    onReady() {
      this.$refs.uForm.setRules(rules);
    },
    async onLoad(props) {
      const system = await getApp().getConfig()
      const userInfo = await getApp().getUserInfo(true)
      if (userInfo) {
        this.userInfo = userInfo
      }
      this.system = system
      this.$u.http.post('list/get', props).then(res => {
        this.content = res[0]
        if (system.show) {
          this.getDiscussList(res[0].company)
        }
      })
    },
    onShareAppMessage() {
      return {
        title: this.content.company,
        path: `/pages/content/index?_id=${this.content._id}`
      }
    },
    methods: {
      showTime(time) {
        uni.showToast({
          icon: 'none',
          title: `发表时间:${this.$u.timeFormat(time, 'yyyy/mm/dd hh:MM:ss')}`
        })
      },
      submit() {
        this.$refs.uForm.validate(valid => {
          if (valid) {
            if (!this.check) return this.$u.toast('请勾选协议');
            uni.showModal({
              content: '是否确认提交',
              success: (r) => {
                if (r.confirm) {
                  this.confirmSubmit()
                }
              }
            })
          } else {
            console.log('验证失败');
          }
        });
      },
      async confirmSubmit() {
        const userInfo = await getApp().getUserInfo()
        if (userInfo) {
          this.userInfo = userInfo
          this.loading = true
          this.$u.http.post('discuss/update', {
            ...this.model,
            company: this.content.company,
            userInfo
          }).then(res => {
            console.log(res)
            if (res.errcode) {
              uni.showToast({
                icon: 'none',
                title: '内容可能含有违法违规内容'
              })
            } else {
              uni.showModal({
                content: '提交成功',
                showCancel: false,
                success: () => {
                  uni.navigateBack()
                }
              })
            }
          }).finally(() => {
            this.loading = false
          })
        }
      },
      getDiscussList(company) {
        this.loadingStatus = 'loading'
        this.$u.http.post('discuss/get', {
            company,
            current: 1,
            pageSize: 100
          })
          .then(res => {
            this.discussList = res
          })
      },
      async updateRate(type) {
        const userInfo = await getApp().getUserInfo()
        if (userInfo) {
          this.userInfo = userInfo
          this.$u.http.post('list/update', {
            _id: this.content._id,
            rate: {
              type,
              userInfo
            }
          }).then(res => {
            this.$u.http.post('list/get', {
              _id: this.content._id
            }).then(res => {
              this.content = res[0]
              uni.showToast({
                icon: 'success',
                title: '打分成功！',
                duration: 2000
              })
            })
          })
        }
      },
      appeal() {
        uni.showModal({
          title: '温馨提示',
          content: '如果内容有误，可以点此纠错，请具体到哪家公司、哪条评论',
          success: (r) => {
            if (r.confirm) {
              uni.navigateTo({
                url: `../feedback/index?id=${this.content._id}&company=${this.content.company}`
              })
            }
          }
        })
      }
    },
    computed: {
      rateConf() {
        const openid = this.userInfo.openid || ''
        const rate = this.content.rate || []
        const rateUp = rate.filter(item => item.type === 1)
        const rateDown = rate.filter(item => item.type === -1)
        const isRate = [...rateUp, ...rateDown].findIndex(item => item.userInfo.openid === openid) !== -1
        return {
          up: {
            type: isRate ? 'success' : 'default',
            rate: isRate ? 0 : 1,
            text: isRate ? rateUp.length : '有价值',
            iconShow: isRate ? true : false
          },
          down: {
            type: isRate ? 'error' : 'default',
            rate: isRate ? 0 : -1,
            text: isRate ? rateDown.length : '无价值',
            iconShow: isRate ? true : false
          }
        }
      }
    }
  }
</script>

<style lang="scss">
  @import './style.scss'
</style>
